/**
 * Project janux-persistence
 * Created by ernesto on 6/9/17.
 */

import {ValidationError} from "../../api/dao/validation-error";

/**
 * Class that helps the defined the errors generated by the daos.
 */
export class ValidationErrorImpl implements ValidationError {
    public attribute: string;
    public message: string;
    public value: string;

    constructor(attribute: string, message: string, value: string) {
        this.attribute = attribute;
        this.message = message;
        this.value = value;
    }
}
